// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package com.neueda.etiqet.rabbitmq;

public final class OrderOuterClass {
  private OrderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:neueda.fix.Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
     */
    int getEventValue();
    /**
     * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
     */
    EnumContainerOuterClass.EnumContainer.EventType getEvent();

    /**
     * <code>string clOrdID = 2;</code>
     */
    java.lang.String getClOrdID();
    /**
     * <code>string clOrdID = 2;</code>
     */
    com.google.protobuf.ByteString
        getClOrdIDBytes();

    /**
     * <code>string origClOrdID = 3;</code>
     */
    java.lang.String getOrigClOrdID();
    /**
     * <code>string origClOrdID = 3;</code>
     */
    com.google.protobuf.ByteString
        getOrigClOrdIDBytes();

    /**
     * <code>string account = 4;</code>
     */
    java.lang.String getAccount();
    /**
     * <code>string account = 4;</code>
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <code>string orderId = 5;</code>
     */
    java.lang.String getOrderId();
    /**
     * <code>string orderId = 5;</code>
     */
    com.google.protobuf.ByteString
        getOrderIdBytes();

    /**
     * <code>string symbol = 6;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>string symbol = 6;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    /**
     * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
     */
    int getSideValue();
    /**
     * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
     */
    EnumContainerOuterClass.EnumContainer.Side getSide();

    /**
     * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
     */
    int getExecInstValue();
    /**
     * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
     */
    EnumContainerOuterClass.EnumContainer.ExecInstType getExecInst();

    /**
     * <code>double quantity = 9;</code>
     */
    double getQuantity();

    /**
     * <code>double outstandingQty = 10;</code>
     */
    double getOutstandingQty();

    /**
     * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
     */
    int getOrderTypeValue();
    /**
     * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
     */
    EnumContainerOuterClass.EnumContainer.OrderType getOrderType();

    /**
     * <code>double price = 12;</code>
     */
    double getPrice();

    /**
     * <code>double stopPrice = 13;</code>
     */
    double getStopPrice();

    /**
     * <code>double minQty = 14;</code>
     */
    double getMinQty();

    /**
     * <code>double maxFloor = 15;</code>
     */
    double getMaxFloor();

    /**
     * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
     */
    int getTimeInForceValue();
    /**
     * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
     */
    EnumContainerOuterClass.EnumContainer.TimeInfoceType getTimeInForce();

    /**
     * <code>fixed64 expireDateTime = 17;</code>
     */
    long getExpireDateTime();
  }
  /**
   * Protobuf type {@code neueda.fix.Order}
   */
  public  static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:neueda.fix.Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      event_ = 0;
      clOrdID_ = "";
      origClOrdID_ = "";
      account_ = "";
      orderId_ = "";
      symbol_ = "";
      side_ = 0;
      execInst_ = 0;
      quantity_ = 0D;
      outstandingQty_ = 0D;
      orderType_ = 0;
      price_ = 0D;
      stopPrice_ = 0D;
      minQty_ = 0D;
      maxFloor_ = 0D;
      timeInForce_ = 0;
      expireDateTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              clOrdID_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              origClOrdID_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              account_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              orderId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              symbol_ = s;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              side_ = rawValue;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              execInst_ = rawValue;
              break;
            }
            case 73: {

              quantity_ = input.readDouble();
              break;
            }
            case 81: {

              outstandingQty_ = input.readDouble();
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              orderType_ = rawValue;
              break;
            }
            case 97: {

              price_ = input.readDouble();
              break;
            }
            case 105: {

              stopPrice_ = input.readDouble();
              break;
            }
            case 113: {

              minQty_ = input.readDouble();
              break;
            }
            case 121: {

              maxFloor_ = input.readDouble();
              break;
            }
            case 128: {
              int rawValue = input.readEnum();

              timeInForce_ = rawValue;
              break;
            }
            case 137: {

              expireDateTime_ = input.readFixed64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderOuterClass.internal_static_neueda_fix_Order_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderOuterClass.internal_static_neueda_fix_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderOuterClass.Order.class, OrderOuterClass.Order.Builder.class);
    }

    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    /**
     * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
     */
    public EnumContainerOuterClass.EnumContainer.EventType getEvent() {
      @SuppressWarnings("deprecation")
      EnumContainerOuterClass.EnumContainer.EventType result = EnumContainerOuterClass.EnumContainer.EventType.valueOf(event_);
      return result == null ? EnumContainerOuterClass.EnumContainer.EventType.UNRECOGNIZED : result;
    }

    public static final int CLORDID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clOrdID_;
    /**
     * <code>string clOrdID = 2;</code>
     */
    public java.lang.String getClOrdID() {
      java.lang.Object ref = clOrdID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clOrdID_ = s;
        return s;
      }
    }
    /**
     * <code>string clOrdID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClOrdIDBytes() {
      java.lang.Object ref = clOrdID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clOrdID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGCLORDID_FIELD_NUMBER = 3;
    private volatile java.lang.Object origClOrdID_;
    /**
     * <code>string origClOrdID = 3;</code>
     */
    public java.lang.String getOrigClOrdID() {
      java.lang.Object ref = origClOrdID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        origClOrdID_ = s;
        return s;
      }
    }
    /**
     * <code>string origClOrdID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOrigClOrdIDBytes() {
      java.lang.Object ref = origClOrdID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        origClOrdID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCOUNT_FIELD_NUMBER = 4;
    private volatile java.lang.Object account_;
    /**
     * <code>string account = 4;</code>
     */
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <code>string account = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDERID_FIELD_NUMBER = 5;
    private volatile java.lang.Object orderId_;
    /**
     * <code>string orderId = 5;</code>
     */
    public java.lang.String getOrderId() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderId_ = s;
        return s;
      }
    }
    /**
     * <code>string orderId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOrderIdBytes() {
      java.lang.Object ref = orderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYMBOL_FIELD_NUMBER = 6;
    private volatile java.lang.Object symbol_;
    /**
     * <code>string symbol = 6;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      }
    }
    /**
     * <code>string symbol = 6;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIDE_FIELD_NUMBER = 7;
    private int side_;
    /**
     * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
     */
    public int getSideValue() {
      return side_;
    }
    /**
     * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
     */
    public EnumContainerOuterClass.EnumContainer.Side getSide() {
      @SuppressWarnings("deprecation")
      EnumContainerOuterClass.EnumContainer.Side result = EnumContainerOuterClass.EnumContainer.Side.valueOf(side_);
      return result == null ? EnumContainerOuterClass.EnumContainer.Side.UNRECOGNIZED : result;
    }

    public static final int EXECINST_FIELD_NUMBER = 8;
    private int execInst_;
    /**
     * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
     */
    public int getExecInstValue() {
      return execInst_;
    }
    /**
     * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
     */
    public EnumContainerOuterClass.EnumContainer.ExecInstType getExecInst() {
      @SuppressWarnings("deprecation")
      EnumContainerOuterClass.EnumContainer.ExecInstType result = EnumContainerOuterClass.EnumContainer.ExecInstType.valueOf(execInst_);
      return result == null ? EnumContainerOuterClass.EnumContainer.ExecInstType.UNRECOGNIZED : result;
    }

    public static final int QUANTITY_FIELD_NUMBER = 9;
    private double quantity_;
    /**
     * <code>double quantity = 9;</code>
     */
    public double getQuantity() {
      return quantity_;
    }

    public static final int OUTSTANDINGQTY_FIELD_NUMBER = 10;
    private double outstandingQty_;
    /**
     * <code>double outstandingQty = 10;</code>
     */
    public double getOutstandingQty() {
      return outstandingQty_;
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 11;
    private int orderType_;
    /**
     * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
     */
    public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
     */
    public EnumContainerOuterClass.EnumContainer.OrderType getOrderType() {
      @SuppressWarnings("deprecation")
      EnumContainerOuterClass.EnumContainer.OrderType result = EnumContainerOuterClass.EnumContainer.OrderType.valueOf(orderType_);
      return result == null ? EnumContainerOuterClass.EnumContainer.OrderType.UNRECOGNIZED : result;
    }

    public static final int PRICE_FIELD_NUMBER = 12;
    private double price_;
    /**
     * <code>double price = 12;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int STOPPRICE_FIELD_NUMBER = 13;
    private double stopPrice_;
    /**
     * <code>double stopPrice = 13;</code>
     */
    public double getStopPrice() {
      return stopPrice_;
    }

    public static final int MINQTY_FIELD_NUMBER = 14;
    private double minQty_;
    /**
     * <code>double minQty = 14;</code>
     */
    public double getMinQty() {
      return minQty_;
    }

    public static final int MAXFLOOR_FIELD_NUMBER = 15;
    private double maxFloor_;
    /**
     * <code>double maxFloor = 15;</code>
     */
    public double getMaxFloor() {
      return maxFloor_;
    }

    public static final int TIMEINFORCE_FIELD_NUMBER = 16;
    private int timeInForce_;
    /**
     * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
     */
    public int getTimeInForceValue() {
      return timeInForce_;
    }
    /**
     * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
     */
    public EnumContainerOuterClass.EnumContainer.TimeInfoceType getTimeInForce() {
      @SuppressWarnings("deprecation")
      EnumContainerOuterClass.EnumContainer.TimeInfoceType result = EnumContainerOuterClass.EnumContainer.TimeInfoceType.valueOf(timeInForce_);
      return result == null ? EnumContainerOuterClass.EnumContainer.TimeInfoceType.UNRECOGNIZED : result;
    }

    public static final int EXPIREDATETIME_FIELD_NUMBER = 17;
    private long expireDateTime_;
    /**
     * <code>fixed64 expireDateTime = 17;</code>
     */
    public long getExpireDateTime() {
      return expireDateTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (event_ != EnumContainerOuterClass.EnumContainer.EventType.NONE_EVT.getNumber()) {
        output.writeEnum(1, event_);
      }
      if (!getClOrdIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clOrdID_);
      }
      if (!getOrigClOrdIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, origClOrdID_);
      }
      if (!getAccountBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, account_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, orderId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, symbol_);
      }
      if (side_ != EnumContainerOuterClass.EnumContainer.Side.NONE_S.getNumber()) {
        output.writeEnum(7, side_);
      }
      if (execInst_ != EnumContainerOuterClass.EnumContainer.ExecInstType.STAY_ON_OFFER_SIDE.getNumber()) {
        output.writeEnum(8, execInst_);
      }
      if (quantity_ != 0D) {
        output.writeDouble(9, quantity_);
      }
      if (outstandingQty_ != 0D) {
        output.writeDouble(10, outstandingQty_);
      }
      if (orderType_ != EnumContainerOuterClass.EnumContainer.OrderType.NONE_ORD.getNumber()) {
        output.writeEnum(11, orderType_);
      }
      if (price_ != 0D) {
        output.writeDouble(12, price_);
      }
      if (stopPrice_ != 0D) {
        output.writeDouble(13, stopPrice_);
      }
      if (minQty_ != 0D) {
        output.writeDouble(14, minQty_);
      }
      if (maxFloor_ != 0D) {
        output.writeDouble(15, maxFloor_);
      }
      if (timeInForce_ != EnumContainerOuterClass.EnumContainer.TimeInfoceType.DAY.getNumber()) {
        output.writeEnum(16, timeInForce_);
      }
      if (expireDateTime_ != 0L) {
        output.writeFixed64(17, expireDateTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (event_ != EnumContainerOuterClass.EnumContainer.EventType.NONE_EVT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, event_);
      }
      if (!getClOrdIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clOrdID_);
      }
      if (!getOrigClOrdIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, origClOrdID_);
      }
      if (!getAccountBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, account_);
      }
      if (!getOrderIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, orderId_);
      }
      if (!getSymbolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, symbol_);
      }
      if (side_ != EnumContainerOuterClass.EnumContainer.Side.NONE_S.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, side_);
      }
      if (execInst_ != EnumContainerOuterClass.EnumContainer.ExecInstType.STAY_ON_OFFER_SIDE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, execInst_);
      }
      if (quantity_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, quantity_);
      }
      if (outstandingQty_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, outstandingQty_);
      }
      if (orderType_ != EnumContainerOuterClass.EnumContainer.OrderType.NONE_ORD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, orderType_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, price_);
      }
      if (stopPrice_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, stopPrice_);
      }
      if (minQty_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(14, minQty_);
      }
      if (maxFloor_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(15, maxFloor_);
      }
      if (timeInForce_ != EnumContainerOuterClass.EnumContainer.TimeInfoceType.DAY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(16, timeInForce_);
      }
      if (expireDateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(17, expireDateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderOuterClass.Order)) {
        return super.equals(obj);
      }
      OrderOuterClass.Order other = (OrderOuterClass.Order) obj;

      boolean result = true;
      result = result && event_ == other.event_;
      result = result && getClOrdID()
          .equals(other.getClOrdID());
      result = result && getOrigClOrdID()
          .equals(other.getOrigClOrdID());
      result = result && getAccount()
          .equals(other.getAccount());
      result = result && getOrderId()
          .equals(other.getOrderId());
      result = result && getSymbol()
          .equals(other.getSymbol());
      result = result && side_ == other.side_;
      result = result && execInst_ == other.execInst_;
      result = result && (
          java.lang.Double.doubleToLongBits(getQuantity())
          == java.lang.Double.doubleToLongBits(
              other.getQuantity()));
      result = result && (
          java.lang.Double.doubleToLongBits(getOutstandingQty())
          == java.lang.Double.doubleToLongBits(
              other.getOutstandingQty()));
      result = result && orderType_ == other.orderType_;
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getStopPrice())
          == java.lang.Double.doubleToLongBits(
              other.getStopPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMinQty())
          == java.lang.Double.doubleToLongBits(
              other.getMinQty()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMaxFloor())
          == java.lang.Double.doubleToLongBits(
              other.getMaxFloor()));
      result = result && timeInForce_ == other.timeInForce_;
      result = result && (getExpireDateTime()
          == other.getExpireDateTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (37 * hash) + CLORDID_FIELD_NUMBER;
      hash = (53 * hash) + getClOrdID().hashCode();
      hash = (37 * hash) + ORIGCLORDID_FIELD_NUMBER;
      hash = (53 * hash) + getOrigClOrdID().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderId().hashCode();
      hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
      hash = (53 * hash) + getSymbol().hashCode();
      hash = (37 * hash) + SIDE_FIELD_NUMBER;
      hash = (53 * hash) + side_;
      hash = (37 * hash) + EXECINST_FIELD_NUMBER;
      hash = (53 * hash) + execInst_;
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQuantity()));
      hash = (37 * hash) + OUTSTANDINGQTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOutstandingQty()));
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + orderType_;
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + STOPPRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getStopPrice()));
      hash = (37 * hash) + MINQTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinQty()));
      hash = (37 * hash) + MAXFLOOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxFloor()));
      hash = (37 * hash) + TIMEINFORCE_FIELD_NUMBER;
      hash = (53 * hash) + timeInForce_;
      hash = (37 * hash) + EXPIREDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireDateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderOuterClass.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderOuterClass.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderOuterClass.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderOuterClass.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderOuterClass.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderOuterClass.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderOuterClass.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderOuterClass.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderOuterClass.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OrderOuterClass.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderOuterClass.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderOuterClass.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderOuterClass.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code neueda.fix.Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:neueda.fix.Order)
        OrderOuterClass.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderOuterClass.internal_static_neueda_fix_Order_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderOuterClass.internal_static_neueda_fix_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderOuterClass.Order.class, OrderOuterClass.Order.Builder.class);
      }

      // Construct using com.neueda.etiqet.rabbitmq.OrderOuterClass.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        event_ = 0;

        clOrdID_ = "";

        origClOrdID_ = "";

        account_ = "";

        orderId_ = "";

        symbol_ = "";

        side_ = 0;

        execInst_ = 0;

        quantity_ = 0D;

        outstandingQty_ = 0D;

        orderType_ = 0;

        price_ = 0D;

        stopPrice_ = 0D;

        minQty_ = 0D;

        maxFloor_ = 0D;

        timeInForce_ = 0;

        expireDateTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderOuterClass.internal_static_neueda_fix_Order_descriptor;
      }

      @java.lang.Override
      public OrderOuterClass.Order getDefaultInstanceForType() {
        return OrderOuterClass.Order.getDefaultInstance();
      }

      @java.lang.Override
      public OrderOuterClass.Order build() {
        OrderOuterClass.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public OrderOuterClass.Order buildPartial() {
        OrderOuterClass.Order result = new OrderOuterClass.Order(this);
        result.event_ = event_;
        result.clOrdID_ = clOrdID_;
        result.origClOrdID_ = origClOrdID_;
        result.account_ = account_;
        result.orderId_ = orderId_;
        result.symbol_ = symbol_;
        result.side_ = side_;
        result.execInst_ = execInst_;
        result.quantity_ = quantity_;
        result.outstandingQty_ = outstandingQty_;
        result.orderType_ = orderType_;
        result.price_ = price_;
        result.stopPrice_ = stopPrice_;
        result.minQty_ = minQty_;
        result.maxFloor_ = maxFloor_;
        result.timeInForce_ = timeInForce_;
        result.expireDateTime_ = expireDateTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderOuterClass.Order) {
          return mergeFrom((OrderOuterClass.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderOuterClass.Order other) {
        if (other == OrderOuterClass.Order.getDefaultInstance()) return this;
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (!other.getClOrdID().isEmpty()) {
          clOrdID_ = other.clOrdID_;
          onChanged();
        }
        if (!other.getOrigClOrdID().isEmpty()) {
          origClOrdID_ = other.origClOrdID_;
          onChanged();
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          onChanged();
        }
        if (!other.getOrderId().isEmpty()) {
          orderId_ = other.orderId_;
          onChanged();
        }
        if (!other.getSymbol().isEmpty()) {
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.side_ != 0) {
          setSideValue(other.getSideValue());
        }
        if (other.execInst_ != 0) {
          setExecInstValue(other.getExecInstValue());
        }
        if (other.getQuantity() != 0D) {
          setQuantity(other.getQuantity());
        }
        if (other.getOutstandingQty() != 0D) {
          setOutstandingQty(other.getOutstandingQty());
        }
        if (other.orderType_ != 0) {
          setOrderTypeValue(other.getOrderTypeValue());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getStopPrice() != 0D) {
          setStopPrice(other.getStopPrice());
        }
        if (other.getMinQty() != 0D) {
          setMinQty(other.getMinQty());
        }
        if (other.getMaxFloor() != 0D) {
          setMaxFloor(other.getMaxFloor());
        }
        if (other.timeInForce_ != 0) {
          setTimeInForceValue(other.getTimeInForceValue());
        }
        if (other.getExpireDateTime() != 0L) {
          setExpireDateTime(other.getExpireDateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderOuterClass.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderOuterClass.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int event_ = 0;
      /**
       * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
       */
      public EnumContainerOuterClass.EnumContainer.EventType getEvent() {
        @SuppressWarnings("deprecation")
        EnumContainerOuterClass.EnumContainer.EventType result = EnumContainerOuterClass.EnumContainer.EventType.valueOf(event_);
        return result == null ? EnumContainerOuterClass.EnumContainer.EventType.UNRECOGNIZED : result;
      }
      /**
       * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
       */
      public Builder setEvent(EnumContainerOuterClass.EnumContainer.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.EventType event = 1;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object clOrdID_ = "";
      /**
       * <code>string clOrdID = 2;</code>
       */
      public java.lang.String getClOrdID() {
        java.lang.Object ref = clOrdID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clOrdID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clOrdID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClOrdIDBytes() {
        java.lang.Object ref = clOrdID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clOrdID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clOrdID = 2;</code>
       */
      public Builder setClOrdID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clOrdID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clOrdID = 2;</code>
       */
      public Builder clearClOrdID() {
        
        clOrdID_ = getDefaultInstance().getClOrdID();
        onChanged();
        return this;
      }
      /**
       * <code>string clOrdID = 2;</code>
       */
      public Builder setClOrdIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clOrdID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object origClOrdID_ = "";
      /**
       * <code>string origClOrdID = 3;</code>
       */
      public java.lang.String getOrigClOrdID() {
        java.lang.Object ref = origClOrdID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          origClOrdID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string origClOrdID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOrigClOrdIDBytes() {
        java.lang.Object ref = origClOrdID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          origClOrdID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string origClOrdID = 3;</code>
       */
      public Builder setOrigClOrdID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        origClOrdID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string origClOrdID = 3;</code>
       */
      public Builder clearOrigClOrdID() {
        
        origClOrdID_ = getDefaultInstance().getOrigClOrdID();
        onChanged();
        return this;
      }
      /**
       * <code>string origClOrdID = 3;</code>
       */
      public Builder setOrigClOrdIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        origClOrdID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <code>string account = 4;</code>
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        account_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder clearAccount() {
        
        account_ = getDefaultInstance().getAccount();
        onChanged();
        return this;
      }
      /**
       * <code>string account = 4;</code>
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        account_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orderId_ = "";
      /**
       * <code>string orderId = 5;</code>
       */
      public java.lang.String getOrderId() {
        java.lang.Object ref = orderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getOrderIdBytes() {
        java.lang.Object ref = orderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderId = 5;</code>
       */
      public Builder setOrderId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 5;</code>
       */
      public Builder clearOrderId() {
        
        orderId_ = getDefaultInstance().getOrderId();
        onChanged();
        return this;
      }
      /**
       * <code>string orderId = 5;</code>
       */
      public Builder setOrderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object symbol_ = "";
      /**
       * <code>string symbol = 6;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string symbol = 6;</code>
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string symbol = 6;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 6;</code>
       */
      public Builder clearSymbol() {
        
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>string symbol = 6;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        symbol_ = value;
        onChanged();
        return this;
      }

      private int side_ = 0;
      /**
       * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
       */
      public int getSideValue() {
        return side_;
      }
      /**
       * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
       */
      public Builder setSideValue(int value) {
        side_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
       */
      public EnumContainerOuterClass.EnumContainer.Side getSide() {
        @SuppressWarnings("deprecation")
        EnumContainerOuterClass.EnumContainer.Side result = EnumContainerOuterClass.EnumContainer.Side.valueOf(side_);
        return result == null ? EnumContainerOuterClass.EnumContainer.Side.UNRECOGNIZED : result;
      }
      /**
       * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
       */
      public Builder setSide(EnumContainerOuterClass.EnumContainer.Side value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        side_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.Side side = 7;</code>
       */
      public Builder clearSide() {
        
        side_ = 0;
        onChanged();
        return this;
      }

      private int execInst_ = 0;
      /**
       * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
       */
      public int getExecInstValue() {
        return execInst_;
      }
      /**
       * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
       */
      public Builder setExecInstValue(int value) {
        execInst_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
       */
      public EnumContainerOuterClass.EnumContainer.ExecInstType getExecInst() {
        @SuppressWarnings("deprecation")
        EnumContainerOuterClass.EnumContainer.ExecInstType result = EnumContainerOuterClass.EnumContainer.ExecInstType.valueOf(execInst_);
        return result == null ? EnumContainerOuterClass.EnumContainer.ExecInstType.UNRECOGNIZED : result;
      }
      /**
       * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
       */
      public Builder setExecInst(EnumContainerOuterClass.EnumContainer.ExecInstType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        execInst_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.ExecInstType execInst = 8;</code>
       */
      public Builder clearExecInst() {
        
        execInst_ = 0;
        onChanged();
        return this;
      }

      private double quantity_ ;
      /**
       * <code>double quantity = 9;</code>
       */
      public double getQuantity() {
        return quantity_;
      }
      /**
       * <code>double quantity = 9;</code>
       */
      public Builder setQuantity(double value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double quantity = 9;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0D;
        onChanged();
        return this;
      }

      private double outstandingQty_ ;
      /**
       * <code>double outstandingQty = 10;</code>
       */
      public double getOutstandingQty() {
        return outstandingQty_;
      }
      /**
       * <code>double outstandingQty = 10;</code>
       */
      public Builder setOutstandingQty(double value) {
        
        outstandingQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double outstandingQty = 10;</code>
       */
      public Builder clearOutstandingQty() {
        
        outstandingQty_ = 0D;
        onChanged();
        return this;
      }

      private int orderType_ = 0;
      /**
       * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
       */
      public int getOrderTypeValue() {
        return orderType_;
      }
      /**
       * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
       */
      public Builder setOrderTypeValue(int value) {
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
       */
      public EnumContainerOuterClass.EnumContainer.OrderType getOrderType() {
        @SuppressWarnings("deprecation")
        EnumContainerOuterClass.EnumContainer.OrderType result = EnumContainerOuterClass.EnumContainer.OrderType.valueOf(orderType_);
        return result == null ? EnumContainerOuterClass.EnumContainer.OrderType.UNRECOGNIZED : result;
      }
      /**
       * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
       */
      public Builder setOrderType(EnumContainerOuterClass.EnumContainer.OrderType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        orderType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.OrderType orderType = 11;</code>
       */
      public Builder clearOrderType() {
        
        orderType_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 12;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 12;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 12;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private double stopPrice_ ;
      /**
       * <code>double stopPrice = 13;</code>
       */
      public double getStopPrice() {
        return stopPrice_;
      }
      /**
       * <code>double stopPrice = 13;</code>
       */
      public Builder setStopPrice(double value) {
        
        stopPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double stopPrice = 13;</code>
       */
      public Builder clearStopPrice() {
        
        stopPrice_ = 0D;
        onChanged();
        return this;
      }

      private double minQty_ ;
      /**
       * <code>double minQty = 14;</code>
       */
      public double getMinQty() {
        return minQty_;
      }
      /**
       * <code>double minQty = 14;</code>
       */
      public Builder setMinQty(double value) {
        
        minQty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double minQty = 14;</code>
       */
      public Builder clearMinQty() {
        
        minQty_ = 0D;
        onChanged();
        return this;
      }

      private double maxFloor_ ;
      /**
       * <code>double maxFloor = 15;</code>
       */
      public double getMaxFloor() {
        return maxFloor_;
      }
      /**
       * <code>double maxFloor = 15;</code>
       */
      public Builder setMaxFloor(double value) {
        
        maxFloor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double maxFloor = 15;</code>
       */
      public Builder clearMaxFloor() {
        
        maxFloor_ = 0D;
        onChanged();
        return this;
      }

      private int timeInForce_ = 0;
      /**
       * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
       */
      public int getTimeInForceValue() {
        return timeInForce_;
      }
      /**
       * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
       */
      public Builder setTimeInForceValue(int value) {
        timeInForce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
       */
      public EnumContainerOuterClass.EnumContainer.TimeInfoceType getTimeInForce() {
        @SuppressWarnings("deprecation")
        EnumContainerOuterClass.EnumContainer.TimeInfoceType result = EnumContainerOuterClass.EnumContainer.TimeInfoceType.valueOf(timeInForce_);
        return result == null ? EnumContainerOuterClass.EnumContainer.TimeInfoceType.UNRECOGNIZED : result;
      }
      /**
       * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
       */
      public Builder setTimeInForce(EnumContainerOuterClass.EnumContainer.TimeInfoceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        timeInForce_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.neueda.fix.EnumContainer.TimeInfoceType timeInForce = 16;</code>
       */
      public Builder clearTimeInForce() {
        
        timeInForce_ = 0;
        onChanged();
        return this;
      }

      private long expireDateTime_ ;
      /**
       * <code>fixed64 expireDateTime = 17;</code>
       */
      public long getExpireDateTime() {
        return expireDateTime_;
      }
      /**
       * <code>fixed64 expireDateTime = 17;</code>
       */
      public Builder setExpireDateTime(long value) {
        
        expireDateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 expireDateTime = 17;</code>
       */
      public Builder clearExpireDateTime() {
        
        expireDateTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:neueda.fix.Order)
    }

    // @@protoc_insertion_point(class_scope:neueda.fix.Order)
    private static final OrderOuterClass.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderOuterClass.Order();
    }

    public static OrderOuterClass.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public OrderOuterClass.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_neueda_fix_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_neueda_fix_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Order.proto\022\nneueda.fix\032\023EnumContainer" +
      ".proto\"\370\003\n\005Order\0222\n\005event\030\001 \001(\0162#.neueda" +
      ".fix.EnumContainer.EventType\022\017\n\007clOrdID\030" +
      "\002 \001(\t\022\023\n\013origClOrdID\030\003 \001(\t\022\017\n\007account\030\004 " +
      "\001(\t\022\017\n\007orderId\030\005 \001(\t\022\016\n\006symbol\030\006 \001(\t\022,\n\004" +
      "side\030\007 \001(\0162\036.neueda.fix.EnumContainer.Si" +
      "de\0228\n\010execInst\030\010 \001(\0162&.neueda.fix.EnumCo" +
      "ntainer.ExecInstType\022\020\n\010quantity\030\t \001(\001\022\026" +
      "\n\016outstandingQty\030\n \001(\001\0226\n\torderType\030\013 \001(" +
      "\0162#.neueda.fix.EnumContainer.OrderType\022\r" +
      "\n\005price\030\014 \001(\001\022\021\n\tstopPrice\030\r \001(\001\022\016\n\006minQ" +
      "ty\030\016 \001(\001\022\020\n\010maxFloor\030\017 \001(\001\022=\n\013timeInForc" +
      "e\030\020 \001(\0162(.neueda.fix.EnumContainer.TimeI" +
      "nfoceType\022\026\n\016expireDateTime\030\021 \001(\006b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          EnumContainerOuterClass.getDescriptor(),
        }, assigner);
    internal_static_neueda_fix_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_neueda_fix_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_neueda_fix_Order_descriptor,
        new java.lang.String[] { "Event", "ClOrdID", "OrigClOrdID", "Account", "OrderId", "Symbol", "Side", "ExecInst", "Quantity", "OutstandingQty", "OrderType", "Price", "StopPrice", "MinQty", "MaxFloor", "TimeInForce", "ExpireDateTime", });
    EnumContainerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
